services:
  db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Contraseña temporal simple
      MYSQL_DATABASE: tieweb_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    image: node:18
    depends_on:
      db:
        condition: service_healthy