services:
  db:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123  # Contraseña super simple
      MYSQL_DATABASE: tieweb_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-prootpass123"] # Sintaxis directa
      interval: 10s
      timeout: 30s  # ¡Más tiempo!